PRAGMA journal_mode=WAL;

CREATE TABLE PROCESS (
    PID            INT    NOT NULL CHECK(PID >= 1),
    EXEC           TEXT   NOT NULL,
    START_TIME     INT    NOT NULL CHECK(START_TIME >= 0),
    IS_ALIVE       INT    NOT NULL CHECK(IS_ALIVE IN (0, 1)),
    INIT_TOTAL_CPU REAL   NOT NULL CHECK(INIT_TOTAL_CPU >= 0),
    PRIMARY KEY (PID)
);

CREATE TABLE CPU (
    CPU_CORE     INT  NOT NULL CHECK(CPU_CORE >= 0),
    MHZ          REAL NOT NULL CHECK(MHZ >= 0),
    TOTAL_CACHE  INT  NOT NULL CHECK(TOTAL_CACHE >= 0),
    PRIMARY KEY (CPU_CORE)
);

CREATE TABLE PROCSTAT (
    PID              INT  NOT NULL,
    TIMESTAMP        INT  NOT NULL CHECK(TIMESTAMP >= 0),
    TOTAL_CPU        REAL NOT NULL CHECK(TOTAL_CPU >= 0),
    PERCENT_CPU      REAL          CHECK(PERCENT_CPU >= 0),
    CPU_CORE         INT,
    VIRTUAL_MEMORY   INT  NOT NULL CHECK(VIRTUAL_MEMORY >= 0),
    RESIDENT_MEMORY  INT  NOT NULL CHECK(RESIDENT_MEMORY >= 0),
    SHARED_MEMORY    INT  NOT NULL CHECK(SHARED_MEMORY >= 0),
    PRIMARY KEY (PID, TIMESTAMP)
    FOREIGN KEY (PID)       REFERENCES PROCESS(PID),
    FOREIGN KEY (CPU_CORE)  REFERENCES CPU(CPU_CORE)
);

CREATE TABLE CPUSTAT (
    CPU_CORE    INT  NOT NULL,
    TIMESTAMP   INT  NOT NULL CHECK(TIMESTAMP >= 0),
    USAGE       REAL NOT NULL CHECK(USAGE >= 0),
    PRIMARY KEY (CPU_CORE, TIMESTAMP)
);

CREATE TABLE MEMORY (
    TIMESTAMP   INT  NOT NULL CHECK(TIMESTAMP >= 0),
    TOTAL       INT  NOT NULL CHECK(TOTAL >= 0),
    FREE        INT  NOT NULL CHECK(FREE >= 0 AND FREE <= TOTAL),
    SWAP_TOTAL  INT  NOT NULL CHECK(SWAP_TOTAL >= 0),
    SWAP_FREE   INT  NOT NULL CHECK(SWAP_FREE >= 0 AND SWAP_FREE <= SWAP_TOTAL),
    PRIMARY KEY (TIMESTAMP)
);

CREATE TABLE DISK (
    DEVICE_NAME TEXT NOT NULL,
    MOUNT       TEXT NOT NULL,
    FS_TYPE     TEXT NOT NULL,
    PRIMARY KEY (DEVICE_NAME)
);

CREATE TABLE DISKSTAT (
    DEVICE_NAME TEXT NOT NULL,
    TIMESTAMP   INT  NOT NULL CHECK(TIMESTAMP >= 0),
    USED        INT  NOT NULL CHECK(USED >= 0),
    AVAILABLE   INT  NOT NULL CHECK(AVAILABLE >= 0),
    PRIMARY KEY (DEVICE_NAME, TIMESTAMP),
    FOREIGN KEY (DEVICE_NAME) REFERENCES DISK(DEVICE_NAME)
);

CREATE TABLE NETWORKINTERFACE (
    NAME     TEXT NOT NULL,
    IP_ADDR  TEXT,
    PRIMARY KEY (NAME)
);

CREATE TABLE NETWORKSTAT (
    NAME                TEXT NOT NULL,
    TIMESTAMP           INT           CHECK(TIMESTAMP >= 0),
    DELTA_BYTES_RECV    INT  NOT NULL CHECK(DELTA_BYTES_RECV >= 0),
    DELTA_BYTES_SENT    INT  NOT NULL CHECK(DELTA_BYTES_SENT >= 0),
    DELTA_PACKETS_RECV  INT  NOT NULL CHECK(DELTA_PACKETS_RECV >= 0),
    DELTA_PACKETS_SENT  INT  NOT NULL CHECK(DELTA_PACKETS_SENT >= 0),
    DELTA_ERR_RECV      INT  NOT NULL CHECK(DELTA_ERR_RECV >= 0),
    DELTA_ERR_SENT      INT  NOT NULL CHECK(DELTA_ERR_SENT >= 0),
    PRIMARY KEY (NAME, TIMESTAMP)
    FOREIGN KEY (NAME) REFERENCES NETWORKINTERFACE(NAME)
);
