#!/bin/sh
set -e

NEBULA_DIR="/var/nebula/"

if [ "$1" != "upgrade" ]; then
    echo "Removing all Nebula Metrics files."
    rm -rf $NEBULA_DIR
else
    echo "Upgrading Nebula Metrics. Skipping postrm file cleanup."
fi

#DEBHELPER#
