baseURL = 'https://joshuaseligman18.github.io/nebula-metrics/'
languageCode = 'en-us'
title = 'Nebula Metrics'

theme = 'hugo-theme-relearn'

[params]
disableSearch = true
disableLandingPageButton = true
disableOpenapi = false

[[params.themeVariant]]
auto = ['zen-light', 'zen-dark']
identifier = 'zen-auto'

[params.imageEffects]
lightbox = false

[menu]
[[menu.shortcuts]]
identifier = 'ds'
name = "<i class='fab fa-fw fa-github'></i> GitHub Repository"
url = 'https://github.com/joshuaseligman18/nebula-metrics'
weight = 10

[module]
[[module.mounts]]
source = 'content'
target = 'content'

[[module.mounts]]
source = 'layouts'
target = 'layouts'

[[module.mounts]]
source = 'static'
target = 'static'
