name: Nebula Metrics Automated Testing

on:
  pull_request:
    branches: main
  push:
    branches: main

permissions:
  contents: read

jobs:
  run-rust-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - name: Install cargo-llvm-cov
      run: cargo install cargo-llvm-cov
    - name: Run tests
      run: cargo llvm-cov --html --no-cfg-coverage --all-features
    - name: Upload Results
      uses: actions/upload-artifact@v4
      with:
        name: rust-code-coverage
        path: target/llvm-cov/html/
        if-no-files-found: error
  run-js-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install dependenices
      run: |
        cd dashboard
        npm install
    - name: Run tests
      run: npm test
    - name: Upload Results
      uses: actions/upload-artifact@v4
      with:
        name: js-code-coverage
        path: coverage/
        if-no-files-found: error
