name: Nebula Metrics Automated Testing

on:
  [pull_request, push]:
      branches: main

permissions:
  contents: read

jobs:
  run-rust-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - name: Install cargo-llvm-cov
      run: cargo install cargo-llvm-cov
    - name: Run tests
      run: cargo llvm-cov --html --no-cfg-coverage --all-features
    - name: Upload Results
      uses: actions/upload-artifact@v4
      with:
        name: rust-code-coverage
        path: target/llvm-cov/html/
        if-no-files-found: error
