[package]
name = "models"
edition = "2021"
version.workspace = true
authors.workspace = true
description = "Common models for both the monitor and server"

[dependencies]
serde.workspace = true
sqlx.workspace = true
